name: systori
version: 0.0.1
description: >
  Systori components written in Dart.
dependencies:
  intl: any
  collection: any
  browser: any
  web_components: any
dev_dependencies:
  test: any
transformers:
- $dart2js:
    minify: true
    commandLineOptions: [
        --trust-type-annotations
        --trust-primitives
    ]
