name: systori
version: 0.0.1
description: >
  Systori components written in Dart.
dependencies:
  intl: any
  web_components: any
  parsers: any
  quiver: any
dev_dependencies:
  test: any
transformers:
  - $dart2js:
      $include: web/job_editor.dart
