name: systori
version: 0.0.1
description: >
  Systori components written in Dart.
dependencies:
  intl: any
  web_components: any
  parsers: any
  quiver:
    git: git://github.com/google/quiver-dart.git
    #path: ../../../quiver-dart
dev_dependencies:
  test: any
transformers:
  - $dart2js:
      $include:
        - web/adjustment_editor.dart
        - web/field.dart
        - web/field_planning.dart
        - web/invoice_editor.dart
        - web/job_editor.dart
        - web/payment_editor.dart
        - web/project_list.dart
        - web/proposal_editor.dart
        - web/refund_editor.dart
        - web/timetracking.dart
      commandLineOptions: [--show-package-warnings]
