name: systori
version: 0.0.1
description: >
  Systori components written in Dart.
dependencies:
  intl: any
  collection: any
  web_components: any
  parsers: any
  quiver: any
dev_dependencies:
  test: any
  mockito: any
