name: systori

# shipmaster 1.0

layers:
  base:
    from: damoti/base:latest
    apt-get:
      - language-pack-de
      - supervisor
    context:
      - requirements/base.pip
    build:
      - pip3 install -r requirements/base.pip
  app:
    context:
      - .
    build:
      - cp conf/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
      - cp systori/dart/sdk/html_dart2js.dart /usr/lib/dart/lib/html/dart2js
      - cd systori/dart && pub get && pub build
      - cd /app
      - pip3 install --src=/src -r requirements/app.pip
      - export DJANGO_SETTINGS_MODULE=systori.settings.common
      - python3 manage.py collectstatic --noinput
    prepare: fab prepare:service={service},branch={git-branch}
    start: /usr/bin/supervisord
    wait-for: db:5432
  test:
    build:
      - pip3 install -r requirements/test.pip
    start: fab test
    wait-for: db:5432

ssh:
  known_hosts:
    - github.com
    - bitbucket.org

build:
  branches:
    - dev

# shipmaster 2.0

branches:
  - :pull
  - dev

stages:
  - base
  - app
  - test
  - deploy

images:

  base:
    from: damoti/base:latest
    context:
      - requirements/base.pip
    build:
      -> apt-get update && apt-get install -y
          language-pack-de
          supervisor
      - pip3 install -r requirements/base.pip
    ssh:
      known_hosts:
        - github.com
        - bitbucket.org

  app:
    from: base
    context:
      - .
    build:
      - cp conf/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
      - cp systori/dart/sdk/html_dart2js.dart /usr/lib/dart/lib/html/dart2js
      - cd systori/dart && pub get && pub build
      - cd /app
      - pip3 install --src=/src -r requirements/app.pip
      - export DJANGO_SETTINGS_MODULE=systori.settings.common
      - python3 manage.py collectstatic --noinput

  django:
    stage: test
    from: app
    build:
      - pip3 install -r requirements/test.pip
    run: fab test
    wait-for: db:5432

  dartium:
    from: damoti/browser-test:latest
    stage: test

  chrome:
    from: damoti/browser-test:latest
    stage: test

  firefox:
    from: damoti/browser-test:latest
    stage: test

  sandbox:
    stage: deploy
    from: app
    run: fab prepare:service={service},branch={git-branch}
    start: /usr/bin/supervisord
    wait-for: db:5432

  production:
    stage: deploy
    from: app
    run: fab prepare:service={service},branch={git-branch}
    start: /usr/bin/supervisord
    wait-for: db:5432

slack:
  events:
    - build.failure
    - test.success
    - test.failure
    - deployment.success
    - deployment.failure
  api: https://hooks.slack.com/services/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
