language: python

python:
  - "3.6"

cache:
  directories:
    - $HOME/virtualenv

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fabric language-pack-de
  - sudo dpkg-reconfigure locales
  - sudo apt-get install apt-transport-https
  - sudo sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
  - sudo sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
  - sudo apt-get update
  - sudo apt-get install dart
  #- fab getdartium
  #- export DART_SDK="$HOME/bin/dart-sdk"
  #- export PATH="$HOME/.pub-cache/bin:$DART_SDK/bin:$PATH"

install:
  - pip install --upgrade pip
  - pip install --upgrade -r requirements/test.pip

before_script:
  - export DJANGO_SETTINGS_MODULE=systori.settings.travis
  - cd systori/dart && /usr/lib/dart/bin/pub get && /usr/lib/dart/bin/pub build && cd ../..
  - psql -c 'create database travisci;' -U postgres

script:
  - python manage.py collectstatic --noinput
  - coverage run -p manage.py test systori.apps systori.lib

after_script:
  - coverage combine
  # - coveralls

branches:
  only:
    - dev

notifications:
  email: m.raesener@gmail.com

addons:
  ssh_known_hosts: bitbucket.org
  sauce_connect: true