language: python

python:
  - "3.4"

cache:
  directories:
    - $HOME/virtualenv

before_install:
  - sudo apt-get install fabric language-pack-de
  - sudo dpkg-reconfigure locales
  - curl http://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-linux-x64-release.zip > $HOME/dartsdk.zip
  - unzip $HOME/dartsdk.zip -d $HOME > /dev/null
  - export DART_SDK="$HOME/dart-sdk"
  - export PATH="$HOME/.pub-cache/bin:$DART_SDK/bin:$PATH"

install:
  - pip install --upgrade pip
  - pip install --upgrade -r requirements/dev.pip

before_script:
  - fab init_settings:env_name=testing
  - cd editor && pub get && pub build && cd ..

script:
  - coverage run -p --branch --source=systori manage.py test systori
  - coverage run -p --branch --source=systori uitest.py saucelabs

after_script:
  - coverage combine
  - coveralls

notifications:
  hipchat: c0d0f5b33bd732300040609176b55c@systori
  email: false

addons:
  ssh_known_hosts: bitbucket.org
  sauce_connect: true
