language: python
python:
  - "3.4"
cache:
  directories:
    - $HOME/virtualenv
before_install:
  - sudo apt-get install fabric
install:
  - pip install --upgrade pip
  - pip install --upgrade -r requirements/common.pip
before_script:
  - fab init_settings:env_name=testing
script:
  - ./manage.py test
notifications:
  hipchat: c0d0f5b33bd732300040609176b55c@systori
  email: false
addons:
  ssh_known_hosts: bitbucket.org
