language: python

python:
  - "3.4"

cache:
  directories:
    - $HOME/virtualenv
    - $HOME/.pub-cache

before_install:
  - sudo apt-get install fabric
    - wget -O /tmp/dartsdk.zip http://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-linux-x64-release.zip
    - unzip /tmp/dartsdk.zip /tmp
    - export DART_SDK=/tmp/dart-sdk
    - export PATH=$DART_SDK/bin:$PATH

install:
  - pip install --upgrade pip
  - pip install --upgrade -r requirements/dev.pip

before_script:
  - fab init_settings:env_name=testing
  - cd editor && pub get && pub build

script:
  - coverage run -p --branch --source=systori manage.py test systori
  - coverage run -p --branch --source=systori uitest.py saucelabs

after_script:
  - coverage combine
  - coveralls

notifications:
  hipchat: c0d0f5b33bd732300040609176b55c@systori
  email: false

addons:
  ssh_known_hosts: bitbucket.org
  sauce_connect: true
