matrix:

  include:
    language: dart
    dart: 1.24.3-1
    script:
      - cd systori/dart/web && /usr/bin/pub get && /usr/bin/pub build && cd ../../..
  
  include:
    language: python
    python: 3.6
    cache:
      directories:
        - $HOME/virtualenv
    before_install:
      - sudo apt-get update -qq
      - sudo apt-get install -qq fabric language-pack-de
      - sudo dpkg-reconfigure locales
      #- fab getdartium
      #- export DART_SDK="$HOME/bin/dart-sdk"
      #- export PATH="$HOME/.pub-cache/bin:$DART_SDK/bin:$PATH"
    install:
      - pip install --upgrade pip
      - pip install --upgrade -r requirements/dev.pip
    before_script:
      - fab initsettings:envname=common
    script:
      - coverage run -p manage.py test systori
    after_script:
      - coverage combine
      - coveralls

  branches:
    only:
      - dev

  notifications:
    email: m.raesener@gmail.com

  addons:
    ssh_known_hosts: bitbucket.org
    sauce_connect: true