dist: xenial
language: python

python:
  - "3.6"

services:
  - postgresql

cache:
  directories:
    - $HOME/virtualenv

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fabric language-pack-de
  - sudo dpkg-reconfigure locales
  - sudo apt-get install apt-transport-https
  - sudo sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
  - sudo sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
  - sudo apt-get update
#  - sudo apt-get install dart=1.24.3-1
  - sudo wget https://storage.googleapis.com/dart-archive/channels/stable/release/1.24.3/sdk/dartsdk-linux-x64-release.zip
  - sudo unzip dartsdk-linux-x64-release.zip

install:
  - pip install --upgrade pip
  - pip install --upgrade -r requirements/test.pip

before_script:
  - export DJANGO_SETTINGS_MODULE=systori.settings.travis
  - export PUSHER_APP_ID=123456
  - export PUSHER_KEY=123456789123456789ab
  - export PUSHER_SECRET=123456789123456789ab
  - cd systori/dart && $TRAVIS_BUILD_DIR/dart-sdk/bin/pub get && $TRAVIS_BUILD_DIR/dart-sdk/bin/pub build && cd ../..
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - python manage.py collectstatic --noinput
  - coverage run -p manage.py test systori.apps systori.lib

after_script:
  - coverage combine
  - codecov

branches:
  only:
    - dev

notifications:
  email: marius@raesener.de

addons:
  ssh_known_hosts: bitbucket.org
  sauce_connect: true