language: python

python:
  - "3.4"

cache:
  directories:
    - $HOME/virtualenv

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fabric language-pack-de
  - sudo dpkg-reconfigure locales
  - fab get_dart
  - export DART_SDK="$HOME/bin/dart-sdk"
  - export PATH="$HOME/.pub-cache/bin:$DART_SDK/bin:$PATH"

install:
  - pip install --upgrade pip
  - pip install --upgrade -r requirements/dev.pip

before_script:
  - fab init_settings:env_name=travis
  - cd systori/dart && pub get && pub build && cd ../..

script:
  - coverage run -p manage.py test systori
  - coverage run -p uitest.py saucelabs

after_script:
  - coverage combine
  - coveralls

branches:
  only:
    - dev

notifications:
  hipchat: c0d0f5b33bd732300040609176b55c@systori
  email: false

addons:
  ssh_known_hosts: bitbucket.org
  sauce_connect: true
