version: "3.6"
services:
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
      args:
        RLEXTRA_ACCESS_TOKEN: $RLEXTRA_ACCESS_TOKEN
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
      DJANGO_SETTINGS_MODULE: 'systori.settings.production'
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    links:
      - postgres
    entrypoint: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    # entrypoint: ["/app/_docker_related/idle.sh"]
  
  postgres:
    image: "postgres:9.5"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  # dart:
  #   image: google/dart:1.24.3
  #   volumes:
  #     - ./systori/dart/:/app:z
  #     - ./_docker_related:/startup:z
  #   entrypoint: /startup/idle.sh