version: '2'
services:
  app:
    environment:
      DJANGO_SETTINGS_MODULE: systori.settings.docker
      SSH_AUTH_SOCK: /tmp/agent.sock
    build: .
    tty: true
    entrypoint: fab
    command: startdocker
    image: systori/local
    volumes:
      - $SSH_AUTH_SOCK:/tmp/agent.sock
      - .:/systori
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
