version: "3"
services:
  app_local:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
      args:
        - REQUIREMENTS_FILE=dev.pip
        - DJANGO_SETTINGS_MODULE=systori.settings.docker_local
        - PUSHER_APP_ID=$PUSHER_APP_ID
        - PUSHER_KEY=$PUSHER_KEY
        - PUSHER_SECRET=$PUSHER_SECRET
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
      DJANGO_SETTINGS_MODULE: 'systori.settings.docker_local'
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PUSHER_APP_ID: $PUSHER_APP_ID
      PUSHER_KEY: $PUSHER_KEY
      PUSHER_SECRET: $PUSHER_SECRET
    links:
      - db
    entrypoint: ["dumb-init", "docker/app/startup.sh"]

  app_sandbox:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
      args:
        - REQUIREMENTS_FILE=dev.pip
        - DJANGO_SETTINGS_MODULE=systori.settings.sandbox
        - PUSHER_APP_ID=$PUSHER_APP_ID
        - PUSHER_KEY=$PUSHER_KEY
        - PUSHER_SECRET=$PUSHER_SECRET
    image: elmcrest/systori:sandbox
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
      DJANGO_SETTINGS_MODULE: 'systori.settings.sandbox'
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PUSHER_APP_ID: $PUSHER_APP_ID
      PUSHER_KEY: $PUSHER_KEY
      PUSHER_SECRET: $PUSHER_SECRET
    links:
      - db
    entrypoint: ["dumb-init", "docker/app/startup.sh"]

  db:
    image: "postgres:9.5"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  db_test:
    image: "postgres:9.5"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    command: -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0

  dart:
    build:
      context: ./
      dockerfile: docker/dart/Dockerfile
    volumes:
      - ./systori/dart/:/app:z
      - /root/.pub-cache/:/root/.pub-cache/:z
      - ./docker:/startup
    entrypoint: /startup/idle.sh
    # create if needed /root/.pub-cache and change owner, add in docker settings
    # `pwd`/docker-compose up -d dart
    # docker exec -it `container id` /bin/bash
    # cd app && pub get && pub build