name: 'systori_editor'
version: 0.0.1
description: >
  Task editor for systori.
dependencies:
  intl: any
  collection: any
  browser: any
transformers:
- $dart2js:
    commandLineOptions: [--enable-enum]
