name: 'systori_editor'
version: 0.0.1
description: >
  Task editor for systori.
dependencies:
  intl: any
  collection: any
  browser: any
  web_components: any
transformers:
- $dart2js:
    minify: true
    commandLineOptions: [
        --trust-type-annotations
        --trust-primitives
    ]
