version: '3'
services:
  app_local:
    build:
      dockerfile: docker/app/docker_local.Dockerfile
    volumes:
      # Mounts the project folder to '/app'. The target path inside the container
      # should match what your application expects.
      - .:/app:z

      # [Optional] If you are using SSH keys w/Git, mount your .ssh folder to
      # /root/.ssh-localhost so we can copy its contents
      # - ~/.ssh:/root/.ssh-localhost:ro

      # Startup script
      - ./docker:/startup

      # VSCode server volume
      # Basically make sure that vscode server and extensions survive a container rebuild
      # To force rebuilding `docker volume rm vscode-server`
      # See https://code.visualstudio.com/docs/remote/containers-advanced#_avoiding-extension-reinstalls-on-container-rebuild
      - vscode-server:/root/.vscode-server

    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    entrypoint: /app/docker/idle.sh

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
  # dart:
  #   volumes:
  #     - ./systori/dart/:/app:z
  #     # - /root/.pub-cache/:/root/.pub-cache/:z
  #     - ./docker:/startup

volumes:
  vscode-server:
